### ISSUE TITLE
doesn't work on ubuntu 20.04 - 22.04

### ISSUE THREAD

**Issue by arielgebel** [ONYXcore/onyx#3]
Doesn't work on ubuntu 20.04 - 22.04:

error while loading shared libraries: libboost_system.so.1.65.1: cannot open shared object file: No such file or directory

**Comment by isezen** [comment]
I'm on Ubuntu 22.04. How can I solve following compile error?

```
onx@tesla ~/onyx (master) [2]> make
Making all in src
make[1]: Entering directory '/home/onx/onyx/src'
make[2]: Entering directory '/home/onx/onyx/src'
make[3]: Entering directory '/home/onx/onyx'
make[3]: Leaving directory '/home/onx/onyx'
  CXX      libbitcoin_server_a-httpserver.o
httpserver.cpp:74:10: error: 'deque' in namespace 'std' does not name a template type
   74 |     std::deque<std::unique_ptr<WorkItem>> queue;
      |          ^~~~~
httpserver.cpp:33:1: note: 'std::deque' is defined in header '<deque>'; did you forget to '#include <deque>'?
   32 | #include <support/events.h>
  +++ |+#include <deque>
   33 |
httpserver.cpp: In member function 'bool WorkQueue<WorkItem>::Enqueue(WorkItem*)':
httpserver.cpp:92:13: error: 'queue' was not declared in this scope; did you mean 'Enqueue'?
   92 |         if (queue.size() >= maxDepth) {
      |             ^~~~~
      |             Enqueue
httpserver.cpp:95:9: error: 'queue' was not declared in this scope; did you mean 'Enqueue'?
   95 |         queue.emplace_back(std::unique_ptr<WorkItem>(item));
      |         ^~~~~
      |         Enqueue
httpserver.cpp: In member function 'void WorkQueue<WorkItem>::Run()':
httpserver.cpp:106:35: error: 'queue' was not declared in this scope; did you mean 'Enqueue'?
  106 |                 while (running && queue.empty())
      |                                   ^~~~~
      |                                   Enqueue
httpserver.cpp:110:31: error: 'queue' was not declared in this scope; did you mean 'Enqueue'?
  110 |                 i = std::move(queue.front());
      |                               ^~~~~
      |                               Enqueue
make[2]: *** [Makefile:6395: libbitcoin_server_a-httpserver.o] Error 1
make[2]: Leaving directory '/home/onx/onyx/src'
make[1]: *** [Makefile:10560: all-recursive] Error 1
make[1]: Leaving directory '/home/onx/onyx/src'
make: *** [Makefile:777: all-recursive] Error 1
```

**Comment by isezen** [comment]
Strangely, `ldd onyxd` command output of compiled binary;

on `arm64` Raspberry Pi is;
```
linux-vdso.so.1 (0x0000ffff9682c000)
libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000ffff95e40000)
libstdc++.so.6 => /lib/aarch64-linux-gnu/libstdc++.so.6 (0x0000ffff95c10000)
libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000ffff95b70000)
libgcc_s.so.1 => /lib/aarch64-linux-gnu/libgcc_s.so.1 (0x0000ffff95b40000)
libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ffff95990000)
/lib/ld-linux-aarch64.so.1 (0x0000ffff967f3000)
```

and on Linux and is;
```
linux-vdso.so.1 (0x00007ffc34557000)
libboost_system.so.1.65.1 => not found
libboost_filesystem.so.1.65.1 => not found
libboost_thread.so.1.65.1 => not found
libboost_chrono.so.1.65.1 => not found
libdb_cxx-4.8.so => not found
libcrypto.so.1.1 => not found
libminiupnpc.so.10 => not found
libevent_pthreads-2.1.so.6 => not found
libevent-2.1.so.6 => not found
libzmq.so.5 => /lib/x86_64-linux-gnu/libzmq.so.5 (0x00007f53b7371000)
libcurl.so.4 => /lib/x86_64-linux-gnu/libcurl.so.4 (0x00007f53b72c9000)
libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f53b67d6000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f53b66ef000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f53b72a9000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f53b72a4000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f53b64c7000)
libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f53b728c000)
libsodium.so.23 => /lib/x86_64-linux-gnu/libsodium.so.23 (0x00007f53b646f000)
libpgm-5.3.so.0 => /lib/x86_64-linux-gnu/libpgm-5.3.so.0 (0x00007f53b641e000)
libnorm.so.1 => /lib/x86_64-linux-gnu/libnorm.so.1 (0x00007f53b62f3000)
libgssapi_krb5.so.2 => /lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f53b629f000)
libnghttp2.so.14 => /lib/x86_64-linux-gnu/libnghttp2.so.14 (0x00007f53b7260000)
libidn2.so.0 => /lib/x86_64-linux-gnu/libidn2.so.0 (0x00007f53b627e000)
librtmp.so.1 => /lib/x86_64-linux-gnu/librtmp.so.1 (0x00007f53b625f000)
libssh.so.4 => /lib/x86_64-linux-gnu/libssh.so.4 (0x00007f53b61f2000)
libpsl.so.5 => /lib/x86_64-linux-gnu/libpsl.so.5 (0x00007f53b61de000)
libssl.so.3 => /lib/x86_64-linux-gnu/libssl.so.3 (0x00007f53b613a000)
libcrypto.so.3 => /lib/x86_64-linux-gnu/libcrypto.so.3 (0x00007f53b5cf8000)
libldap-2.5.so.0 => /lib/x86_64-linux-gnu/libldap-2.5.so.0 (0x00007f53b5c99000)
liblber-2.5.so.0 => /lib/x86_64-linux-gnu/liblber-2.5.so.0 (0x00007f53b5c88000)
libzstd.so.1 => /lib/x86_64-linux-gnu/libzstd.so.1 (0x00007f53b5bb9000)
libbrotlidec.so.1 => /lib/x86_64-linux-gnu/libbrotlidec.so.1 (0x00007f53b5bab000)
libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f53b5b8f000)
/lib64/ld-linux-x86-64.so.2 (0x00007f53b7423000)
libmd.so.0 => /lib/x86_64-linux-gnu/libmd.so.0 (0x00007f53b5b82000)
libkrb5.so.3 => /lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f53b5ab7000)
libk5crypto.so.3 => /lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f53b5a88000)
libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f53b7254000)
libkrb5support.so.0 => /lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f53b5a7a000)
libunistring.so.2 => /lib/x86_64-linux-gnu/libunistring.so.2 (0x00007f53b58d0000)
libgnutls.so.30 => /lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007f53b56e5000)
libhogweed.so.6 => /lib/x86_64-linux-gnu/libhogweed.so.6 (0x00007f53b569d000)
libnettle.so.8 => /lib/x86_64-linux-gnu/libnettle.so.8 (0x00007f53b5657000)
libgmp.so.10 => /lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f53b55d5000)
libsasl2.so.2 => /lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007f53b55ba000)
libbrotlicommon.so.1 => /lib/x86_64-linux-gnu/libbrotlicommon.so.1 (0x00007f53b5597000)
libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f53b558e000)
libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f53b557a000)
libp11-kit.so.0 => /lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f53b543f000)
libtasn1.so.6 => /lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f53b5427000)
libffi.so.8 => /lib/x86_64-linux-gnu/libffi.so.8 (0x00007f53b541a000)
```
